In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Tạo bộ dữ liệu chính từ các file dữ liệu

In [2]:
df1 = pd.read_csv('data/IMDB Top Movies(1-500).csv', encoding='latin1')

In [3]:
df1 = pd.read_csv('data/IMDB Top Movies(1-500).csv', encoding='latin1')
df2 = pd.read_csv('data/IMDB Top Movies(501-1000).csv', encoding='latin1')
df3 = pd.read_csv('data/IMDB Top Movies(3001-3300).csv')
df4 = pd.read_csv('data/IMDB Top Movies(3301-3800).csv')
df5 = pd.read_csv('data/IMDB Top Movies(4000-4200).csv')
df6 = pd.read_csv('data/TMDB Movies.csv')
df7 = pd.read_csv('data/Tomatoes_Top_Movies.csv')

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Link          500 non-null    object
 1   Movie_Name          500 non-null    object
 2   Ratings             475 non-null    float64
 3   Taglines            350 non-null    object
 4   Movie_category      500 non-null    object
 5   Film_Actor          500 non-null    object
 6   Release_Date        500 non-null    object
 7   Duration            451 non-null    object
 8   Country             500 non-null    object
 9   Original_Language   497 non-null    object
 10  Companies           497 non-null    object
 11  Description         500 non-null    object
 12  Budget              139 non-null    object
 13  Box Office          128 non-null    object
 14  Certificate (MPAA)  452 non-null    object
 15  Directors           500 non-null    object
 16  Writing_Credits     499 non-null    object
 17  poster_path         500 non-null    object
dtypes: float64(1), object(17)
memory usage: 70.4+ KB

In [5]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Movie_Link         240 non-null    object
 1   Movie_Name         240 non-null    object
 2   Ratings            239 non-null    object
 3   Movie_category     239 non-null    object
 4   Film_Actor         240 non-null    object
 5   Release_Date       239 non-null    object
 6   Duration           236 non-null    object
 7   Original_Language  239 non-null    object
 8   Description        239 non-null    object
 9   Box Office         239 non-null    object
 10  Budget             239 non-null    object
 11  Directors          239 non-null    object
 12  Writing_Credits    131 non-null    object
 13  poster_path        240 non-null    object
dtypes: object(14)
memory usage: 26.4+ KB

In [6]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Link          396 non-null    object
 1   Movie_Name          396 non-null    object
 2   Ratings             390 non-null    object
 3   Movie_category      396 non-null    object
 4   Film_Actor          396 non-null    object
 5   Release_Date        396 non-null    object
 6   Duration            396 non-null    object
 7   Original_Language   396 non-null    object
 8   Companies           393 non-null    object
 9   Description         396 non-null    object
 10  Box Office          290 non-null    object
 11  Certificate (MPAA)  351 non-null    object
 12  Directors           395 non-null    object
 13  Writing_Credits     391 non-null    object
 14  poster_path         396 non-null    object
dtypes: object(15)
memory usage: 46.5+ KB

In [7]:
print(df1.columns)
print(df2.columns)
print(df3.columns)
print(df4.columns)
print(df5.columns)
print(df6.columns)
print(df7.columns)

Index(['Movie_Link', 'Movie_Name', 'Ratings', 'Taglines', 'Movie_category',
       'Film_Actor', 'Release_Date', 'Duration', 'Country',
       'Original_Language', 'Companies', 'Description', 'Budget', 'Box Office',
       'Certificate (MPAA)', 'Directors', 'Writing_Credits', 'poster_path'],
      dtype='object')
Index(['Movie_Link', 'Movie_Name', 'Ratings', 'Taglines', 'Movie_category',
       'Film_Actor', 'Release_Date', 'Duration', 'Country',
       'Original_Language', 'Companies', 'Description', 'Budget', 'Box Office',
       'Certificate (MPAA)', 'Directors', 'Writing_Credits', 'poster_path'],
      dtype='object')
Index(['Movie_Link', 'Movie_Name', 'Ratings', 'Movie_category', 'Film_Actor',
       'Release_Date', 'Duration', 'Country', 'Original_Language', 'Companies',
       'Description', 'Budget', 'Box Office', 'Certificate (MPAA)',
       'Directors', 'Writing_Credits', 'poster_path'],
      dtype='object')
Index(['Movie_Link', 'Movie_Name', 'Ratings', 'Movie_category', 'Film_Actor',
       'Release_Date', 'Duration', 'Country', 'Original_Language', 'Companies',
       'Description', 'Budget', 'Box Office', 'Certificate (MPAA)',
       'Directors', 'Writing_Credits', 'poster_path'],
      dtype='object')
Index(['Movie_Link', 'Movie_Name', 'Ratings', 'Movie_category', 'Film_Actor',
       'Release_Date', 'Duration', 'Country', 'Original_Language', 'Companies',
       'Description', 'Budget', 'Box Office', 'Certificate (MPAA)',
       'Directors', 'Writing_Credits', 'poster_path'],
      dtype='object')
Index(['Movie_Link', 'Movie_Name', 'Ratings', 'Movie_category', 'Film_Actor',
       'Release_Date', 'Duration', 'Original_Language', 'Description',
       'Box Office', 'Budget', 'Directors', 'Writing_Credits', 'poster_path'],
      dtype='object')
Index(['Movie_Link', 'Movie_Name', 'Ratings', 'Movie_category', 'Film_Actor',
       'Release_Date', 'Duration', 'Original_Language', 'Companies',
       'Description', 'Box Office', 'Certificate (MPAA)', 'Directors',
       'Writing_Credits', 'poster_path'],
      dtype='object')

Ý nghĩa các thuộc tính:

* **Movie_link**: đường dẫn tới trang web có thông tin chi tiết về bộ phim
* **Movie_name**: Tên bộ phim
* **Ratings**: Điểm số đánh giá bộ phim
* **Taglines**: Câu khẩu hiệu hoặc câu châm ngôn quảng cáo được sử dụng để mô tả bộ phim. (3,4)
* **Movie_category**: Thể loại của bộ phim.
* **Film_actor**: Các diễn viên chính hoặc các vai diễn quan trọng trong bộ phim.
* **Release_Date**: Ngày phát hành chính thức của bộ phim.
* **Duration**: Thời lượng của bộ phim, thường được đo bằng phút.
* **Country**: Quốc gia mà bộ phim được sản xuất hoặc liên quan đến. (3,4)
* **Original_Language**: Ngôn ngữ gốc được sử dụng trong bộ phim.
* **Companies**: Các công ty hoặc hãng sản xuất, phân phối, hoặc hỗ trợ sản xuất bộ phim. (3)
* **Description**: Mô tả ngắn gọn về nội dung của bộ phim.
* **Budget**: Ngân sách sản xuất của bộ phim, tức là số tiền đã chi tiêu để sản xuất. (4)
* **Box Office**: Doanh thu thu được từ việc chiếu phim, thường được đo trong khoản tiền.
* **Certificate (MPAA)**: Chứng nhận phim của Hiệp hội Phim Mỹ (MPAA), đánh giá mức độ phù hợp với khán giả ở mọi độ tuổi. (3)
* **Directors**: Đạo diễn hoặc các nhà làm phim chịu trách nhiệm chỉ đạo quá trình sản xuất và sáng tác của bộ phim.
* **Writing_Credits**: Tác giả hoặc các nhà biên kịch đóng góp vào kịch bản hoặc cốt truyện của bộ phim.
* **poster_path**: Đường dẫn tới poster bộ phim.

Có 5 cột không tồn tại ở cả 4 datasets là: Taglines, Country, Companies, Budget, Certificate (MPAA). Mục đích sử dụng của bộ dữ liệu là để đào tào mô hình khuyến nghị phim, do đó, chúng tôi tự đánh giá theo kinh nghiệm và thực hiện xóa 3 cột là Taglines, Companies, Budget. Cột 'Country' sẽ thêm vào 2 bộ dữ liệu còn thiếu với giá trị 'không rõ' và cột 'Certificate (MPAA)' được giữ lại để đánh giá độ tuổi phù hợp xem phim.

In [8]:
df1 = df1.drop(columns=['Taglines', 'Companies', 'Budget'], axis=1)

In [9]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Link          500 non-null    object
 1   Movie_Name          500 non-null    object
 2   Ratings             475 non-null    float64
 3   Movie_category      500 non-null    object
 4   Film_Actor          500 non-null    object
 5   Release_Date        500 non-null    object
 6   Duration            451 non-null    object
 7   Country             500 non-null    object
 8   Original_Language   497 non-null    object
 9   Description         500 non-null    object
 10  Box Office          128 non-null    object
 11  Certificate (MPAA)  452 non-null    object
 12  Directors           500 non-null    object
 13  Writing_Credits     499 non-null    object
 14  poster_path         500 non-null    object
dtypes: float64(1), object(14)
memory usage: 58.7+ KB

In [10]:
df2 = df2.drop(columns=['Taglines', 'Companies', 'Budget'], axis=1)
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Link          500 non-null    object
 1   Movie_Name          500 non-null    object
 2   Ratings             479 non-null    float64
 3   Movie_category      500 non-null    object
 4   Film_Actor          500 non-null    object
 5   Release_Date        499 non-null    object
 6   Duration            462 non-null    object
 7   Country             500 non-null    object
 8   Original_Language   498 non-null    object
 9   Description         500 non-null    object
 10  Box Office          234 non-null    object
 11  Certificate (MPAA)  441 non-null    object
 12  Directors           500 non-null    object
 13  Writing_Credits     497 non-null    object
 14  poster_path         500 non-null    object
dtypes: float64(1), object(14)
memory usage: 58.7+ KB

In [11]:
df3 = df3.drop(columns=['Companies', 'Budget'], axis=1)
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Link          300 non-null    object
 1   Movie_Name          300 non-null    object
 2   Ratings             289 non-null    float64
 3   Movie_category      300 non-null    object
 4   Film_Actor          300 non-null    object
 5   Release_Date        294 non-null    object
 6   Duration            281 non-null    object
 7   Country             300 non-null    object
 8   Original_Language   297 non-null    object
 9   Description         300 non-null    object
 10  Box Office          150 non-null    object
 11  Certificate (MPAA)  263 non-null    object
 12  Directors           298 non-null    object
 13  Writing_Credits     298 non-null    object
 14  poster_path         300 non-null    object
dtypes: float64(1), object(14)
memory usage: 35.3+ KB

In [12]:
df4 = df4.drop(columns=[ 'Companies', 'Budget'], axis=1)
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Link          500 non-null    object
 1   Movie_Name          500 non-null    object
 2   Ratings             486 non-null    float64
 3   Movie_category      500 non-null    object
 4   Film_Actor          500 non-null    object
 5   Release_Date        496 non-null    object
 6   Duration            472 non-null    object
 7   Country             499 non-null    object
 8   Original_Language   497 non-null    object
 9   Description         500 non-null    object
 10  Box Office          264 non-null    object
 11  Certificate (MPAA)  453 non-null    object
 12  Directors           496 non-null    object
 13  Writing_Credits     492 non-null    object
 14  poster_path         500 non-null    object
dtypes: float64(1), object(14)
memory usage: 58.7+ KB

In [13]:
df5 = df5.drop(columns=[ 'Companies', 'Budget'], axis=1)
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 201 entries, 0 to 200
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Link          201 non-null    object
 1   Movie_Name          201 non-null    object
 2   Ratings             196 non-null    float64
 3   Movie_category      201 non-null    object
 4   Film_Actor          201 non-null    object
 5   Release_Date        199 non-null    object
 6   Duration            189 non-null    object
 7   Country             201 non-null    object
 8   Original_Language   195 non-null    object
 9   Description         201 non-null    object
 10  Box Office          99 non-null     object
 11  Certificate (MPAA)  182 non-null    object
 12  Directors           199 non-null    object
 13  Writing_Credits     199 non-null    object
 14  poster_path         201 non-null    object
dtypes: float64(1), object(14)
memory usage: 23.7+ KB

In [14]:
df6['Country'] = 'khong ro'
df7['Country'] = 'khong ro'

In [15]:
df6 = df6.drop(columns=['Budget'], axis=1)
df6['Certificate (MPAA)'] = 'khong ro'
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Link          240 non-null    object
 1   Movie_Name          240 non-null    object
 2   Ratings             239 non-null    object
 3   Movie_category      239 non-null    object
 4   Film_Actor          240 non-null    object
 5   Release_Date        239 non-null    object
 6   Duration            236 non-null    object
 7   Original_Language   239 non-null    object
 8   Description         239 non-null    object
 9   Box Office          239 non-null    object
 10  Directors           239 non-null    object
 11  Writing_Credits     131 non-null    object
 12  poster_path         240 non-null    object
 13  Country             240 non-null    object
 14  Certificate (MPAA)  240 non-null    object
dtypes: object(15)
memory usage: 28.3+ KB

In [16]:

df6.head(5)

,Movie_Link,Movie_Name,Ratings,Movie_category,Film_Actor,Release_Date,Duration,Original_Language,Description,Box Office,Directors,Writing_Credits,poster_path,Country,Certificate (MPAA)
0,https://www.themoviedb.org/movie/653346-kingdo...,Hành Tinh Khỉ: Vương Quốc Mới,72%,"Phim Khoa Học Viễn Tưởng, Phim Phiêu Lưu, Phim...","[('Owen Teague', 'Noa'), ('Freya Allan', 'Nova...",05/10/2024 (VN),2h 25m,Tiếng Anh,Phim lấy bối cảnh nhiều năm sau triều đại của ...,-,Wes Ball,NaN,posters3/poster_1.jpg,khong ro,khong ro
1,https://www.themoviedb.org/movie/940721-1-0,Quái Vật Godzilla Trừ Một,77%,"Phim Khoa Học Viễn Tưởng, Phim Kinh Dị, Phim H...","[('Ryunosuke Kamiki', 'Koichi Shikishima'), ('...",11/03/2023 (JP),2h 5m,Tiếng Nhật,Lấy bối cảnh 2 năm sau khi Thế chiến thứ hai k...,"$115,857,413.00",Takashi Yamazaki,Takashi Yamazaki,posters3/poster_2.jpg,khong ro,khong ro
2,https://www.themoviedb.org/movie/967847-ghostb...,Biệt Đội Săn Ma: Kỷ Nguyên Băng Giá,67%,"Phim Giả Tượng, Phim Phiêu Lưu, Phim Hài","[('Mckenna Grace', 'Phoebe Spengler'), ('Paul ...",03/22/2024 (US),1h 55m,Tiếng Anh,Chuyện phim kể về gia đình Spengler quyết định...,"$195,102,874.00",Gil Kenan,NaN,posters3/poster_3.jpg,khong ro,khong ro
3,https://www.themoviedb.org/movie/1111873-abigail,Abigail,71%,"Phim Kinh Dị, Phim Gây Cấn","[('Melissa Barrera', 'Joey'), ('Dan Stevens', ...",05/17/2024 (VN),1h 49m,Tiếng Anh,Một nhóm tội phạm bắt cóc một diễn viên ba lê ...,"$28,536,335.00","Tyler Gillett, Matt Bettinelli-Olpin","Stephen Shields, Guy Busick",posters3/poster_4.jpg,khong ro,khong ro
4,https://www.themoviedb.org/movie/823464-godzil...,Godzilla x Kong: Đế Chế Mới,65%,"Phim Hành Động, Phim Khoa Học Viễn Tưởng, Phim...","[('Rebecca Hall', 'Dr. Ilene Andrews'), ('Bria...",03/29/2024 (VN),1h 55m,Tiếng Anh,Kong và Godzilla - hai sinh vật vĩ đại huyền t...,"$546,503,756.00",Adam Wingard,"Terry Rossio, Simon Barrett, Jeremy Slater",posters3/poster_5.jpg,khong ro,khong ro

In [17]:
df7.head(5)

,Movie_Link,Movie_Name,Ratings,Movie_category,Film_Actor,Release_Date,Duration,Original_Language,Companies,Description,Box Office,Certificate (MPAA),Directors,Writing_Credits,poster_path,Country
0,https://www.rottentomatoes.com/m/unfrosted,Unfrosted,41%,Comedy,"['Jerry Seinfeld', 'Jerry Seinfeld', 'Melissa ...",03-May-24,1h 33m,English,"Columbus 81 Productions,Netflix Studios","Michigan, 1963. Kellogg's and Post, sworn cere...",NaN,PG-13 (Language|Some Suggestive References),Jerry Seinfeld,"Jerry Seinfeld, Spike Feresten, Barry Marder, ...",posters4/poster_1.jpg,khong ro
1,https://www.rottentomatoes.com/m/the_idea_of_you,The Idea of You,82%,"Drama, Comedy, Romance","['Michael Showalter', 'Anne Hathaway', 'Nichol...",02-May-24,1h 55m,English,"Somewhere Pictures,Amazon Studios,I'll Have An...","Based on the acclaimed, contemporary love stor...",NaN,R (Sexual Content|Some Language),Michael Showalter,"Michael Showalter, Jennifer Westfeldt",posters4/poster_2.jpg,khong ro
2,https://www.rottentomatoes.com/m/late_night_wi...,Late Night with the Devil,96%,"Mystery & Thriller, Horror","['Colin Cairnes', 'Cameron Cairnes', 'David Da...",19-Apr-24,1h 33m,English,"Future Pictures,Spooky Pictures",Johnny Carson rival Jack Delroy hosts a syndic...,$9.9M,R (Some Gore|Language|A Sexual Reference|Viole...,"Colin Cairnes, Cameron Cairnes","Colin Cairnes, Cameron Cairnes",posters4/poster_3.jpg,khong ro
3,https://www.rottentomatoes.com/m/monkey_man,Monkey Man,89%,"Mystery & Thriller, Action","['Dev Patel', 'Dev Patel', 'Sharlto Copley', '...",23-Apr-24,1h 53m,English,"S'Ya Concept,BRON Studios,Minor Realm,Monkeypa...","Inspired by the legend of Hanuman, an icon emb...",$23.9M,R (Sexual Content/Nudity|Language Throughout|D...,Dev Patel,"Dev Patel, Paul Angunawela, John Collee",posters4/poster_4.jpg,khong ro
4,https://www.rottentomatoes.com/m/turtles_all_t...,Turtles All the Way Down,88%,"Drama, Romance","['Hannah Marks', 'Isabela Merced', 'Cree Cicch...",02-May-24,1h 51m,English,"New Line Cinema,Temple Hill Entertainment",Turtles All the Way Down tackles anxiety throu...,NaN,PG-13,Hannah Marks,"Elizabeth Berger, Isaac Aptaker",posters4/poster_5.jpg,khong ro

In [18]:
df7 = df7.drop(columns=['Companies'], axis=1)
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 396 entries, 0 to 395
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Movie_Link          396 non-null    object
 1   Movie_Name          396 non-null    object
 2   Ratings             390 non-null    object
 3   Movie_category      396 non-null    object
 4   Film_Actor          396 non-null    object
 5   Release_Date        396 non-null    object
 6   Duration            396 non-null    object
 7   Original_Language   396 non-null    object
 8   Description         396 non-null    object
 9   Box Office          290 non-null    object
 10  Certificate (MPAA)  351 non-null    object
 11  Directors           395 non-null    object
 12  Writing_Credits     391 non-null    object
 13  poster_path         396 non-null    object
 14  Country             396 non-null    object
dtypes: object(15)
memory usage: 46.5+ KB

In [19]:
df = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True)
df.shape

(2241, 15)

In [20]:
df[1630:]

,Movie_Link,Movie_Name,Ratings,Movie_category,Film_Actor,Release_Date,Duration,Country,Original_Language,Description,Box Office,Certificate (MPAA),Directors,Writing_Credits,poster_path
1630,https://www.imdb.com/title/tt11127680/?ref_=sr...,Boiling Point,7.5,"Drama, Thriller","Stephen Graham, Vinette Robinson, Alice Feetha...","January 7, 2022 (United Kingdom)",1 hour 32 minutes,United Kingdom,English,Enter the relentless pressure of a restaurant ...,"$1,426,916",R,Philip Barantini,"Philip Barantini, James Cummings",https://m.media-amazon.com/images/M/MV5BZTA0Nz...
1631,https://www.imdb.com/title/tt15293240/?ref_=sr...,Flowers in the Attic: The Origin,7.3,Drama,"Jemima Rooper, Max Irons, T'Shan Williams, Eve...","July 9, 2022 (United States)",1 hour 25 minutes,United States,English,This limited series tells the origin story of ...,NaN,NaN,"Declan O'Dwyer, Robin Sheppard","Virginia C. Andrews, Paul Sciarrotta, Conner G...",https://m.media-amazon.com/images/M/MV5BZmU0OD...
1632,https://www.imdb.com/title/tt2402157/?ref_=sr_...,The November Man,6.3,"Action, Adventure, Crime","Pierce Brosnan, Luke Bracey, Olga Kurylenko, B...","August 27, 2014 (United States)",1 hour 48 minutes,United States,English,An ex-C.I.A. operative is brought back in on a...,"$39,661,919",R,Roger Donaldson,"Michael Finch, Karl Gajdusek, Bill Granger",https://m.media-amazon.com/images/M/MV5BNTkzMD...
1633,https://www.imdb.com/title/tt21810682/?ref_=sr...,The End We Start From,5.9,"Drama, Thriller","Jodie Comer, Joel Fry, Yves Rassou, Ramanique ...","January 19, 2024 (United States)",1 hour 42 minutes,United Kingdom,English,A woman tries to find her way home with her ne...,"$1,354,890",R,Mahalia Belo,"Alice Birch, Megan Hunter",https://m.media-amazon.com/images/M/MV5BZmZkZG...
1634,https://www.imdb.com/title/tt0099077/?ref_=sr_...,Awakenings,7.8,"Biography, Drama","Robert De Niro, Robin Williams, Julie Kavner, ...","January 11, 1991 (United States)",2 hours 1 minute,United States,English,The victims of an encephalitis epidemic many y...,"$52,096,475",PG-13,Penny Marshall,"Oliver Sacks, Steven Zaillian",https://m.media-amazon.com/images/M/MV5BMWUxOT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2236,https://www.themoviedb.org/movie/275-fargo,Đi Quá Xa,79%,"Phim Hình Sự, Phim Chính Kịch, Phim Gây Cấn","[('Frances McDormand', 'Marge Gunderson'), ('W...",03/08/1996 (US),1h 38m,khong ro,Tiếng Anh,Jerry thuê người bắt cóc vợ mình và lợi dụng c...,"$60,611,975.00",khong ro,"Joel Coen, Ethan Coen","Joel Coen, Ethan Coen",posters3/poster_236.jpg
2237,https://www.themoviedb.org/movie/8467-dumb-and...,Siêu Ngốc Gặp Nhau,66%,Phim Hài,"[('Jim Carrey', 'Lloyd Christmas'), ('Jeff Dan...",12/16/1994 (US),1h 47m,khong ro,Tiếng Anh,Dumb and Dumber là một loạt phim hài với sự th...,"$247,275,374.00",khong ro,Peter Farrelly,NaN,posters3/poster_237.jpg
2238,https://www.themoviedb.org/movie/508883,Thiếu Niên Và Chim Diệc,74%,"Phim Hoạt Hình, Phim Phiêu Lưu, Phim Giả Tượng","[('Soma Santoki', 'Mahito Maki (voice)'), ('Ma...",12/15/2023 (VN),2h 4m,khong ro,Tiếng Nhật,Đến từ Studio Ghibli và đạo diễn Miyazaki Haya...,"$165,208,613.00",khong ro,Hayao Miyazaki,NaN,posters3/poster_238.jpg
2239,https://www.themoviedb.org/movie/76341-mad-max...,Max Điên: Con Đường Tử Thần,76%,"Phim Hành Động, Phim Phiêu Lưu, Phim Khoa Học ...","[('Tom Hardy', 'Max Rockatansky'), ('Charlize ...",05/15/2015 (VN),2h,khong ro,Tiếng Anh,Mad Max: Fury Road đưa người xem đến với một t...,"$378,858,340.00",khong ro,George Miller,NaN,posters3/poster_239.jpg
2240,https://www.themoviedb.org/movie/1257750,Honeymoonish,70%,"Phim Lãng Mạn, Phim Hài","[('Nour Al-Ghandour', 'نور'), ('Mahmoud Bousha...",04/29/2024 (US),1h 40m,khong ro,Tiếng A Rập,Two newlyweds on their honeymoon discover that...,-,khong ro,Elie El Semaan,NaN,posters3/poster_240.jpg

In [21]:
df.to_csv('movies.csv', index=False)